CREATE TABLE "GCG_6749_AR_DISC" (
 "TRMNL" CHAR(3),
 "RPTID" CHAR(6),
 "CUSTOMER" CHAR(6),
 "NAME" CHAR(30),
 "DISC_AMT" DOUBLE,
 "DISC_COMM" DOUBLE );
CREATE INDEX "GCG_6749_AR_DISC" ON "GCG_6749_AR_DISC" ( "TRMNL", "RPTID", "CUSTOMER" );
